### ISSUE TITLE
Skylake 睡眠问题解决方法(不完美) Skylake issue (isn't perfect )

### ISSUE THREAD

**Issue by chunma26** [SukkaW/OpenCore-Document-zh_Hans#43]
当Skylake 架构的CPU 在config勾选了AppleXcpuforceboost 睡眠唤醒显示器能正常显示画面，但CPU一直是满频的，希望官方能就这个问题改善一下，现在好像全网都没有Skylake 睡眠的解决方案，但这好像就解决了一半的唤醒的问题，不过CPU会满频和系统自己睡眠就唤醒不了，我把配置图放在了下面

When Skylake CPU tick the AppleXcpuforceboost in config , the screen can wake up after sleeping but the CPU is full frequency all the time.Wish official can solve this problem. I can see that on google baidu is no one can solve the Skylake wake up problem , this way can solve half of problem,but there's a problem that can't wake up from system automatic sleep ,and the CPU full frequency all the time . I put my build at the end.

![A8D40443-D796-4F81-8122-E4B9C2C44824](https://user-images.githubusercontent.com/56785635/112120819-905c0780-8bf9-11eb-9a6e-02e6fdaaed79.jpeg)

**Comment by SukkaW** [comment]
The project is not affiliated with acidanthera. Please open your issue at https://github.com/acidanthera/bugtracker/
