### ISSUE TITLE
Contact OpenCORE developers

### ISSUE THREAD

**Issue by czaq1120** [SukkaW/OpenCore-Document-zh_Hans#45]
OpenCORE guides developers to have a project to seek cooperation, leaving contact information and platform chat tools

**Comment by czaq1120** [comment]
联系方式skype ID983117327@qq.com    ID2332720522@qq.com

**Comment by Z-fly** [comment]
你是OpenCore官方人员吗？

**Comment by SukkaW** [comment]
> 你是OpenCore官方人员吗？

Of course, he isn't. He even joins GitHub a month ago. I am reporting his account to GitHub Support Team now.
